name: Deploy Lambda and Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install and Package Lambda
      run: |
        cd lambda
        npm install
        npm run package

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      working-directory: terraform
      run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=fiap.hackathon.notification.infra.tfstate" -backend-config="region=us-east-1"

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -var="cognito_user_pool_id=${{ secrets.COGNITO_USER_POOL_ID }}" -var="sqs_status_queue_url=${{ secrets.SQS_STATUS_QUEUE_URL }}" -auto-approve

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -var="cognito_user_pool_id=${{ secrets.COGNITO_USER_POOL_ID }}" -var="sqs_status_queue_url=${{ secrets.SQS_STATUS_QUEUE_URL }}" -auto-approve